### ISSUE TITLE
No base connected error.

### ISSUE THREAD

**Issue by garrickb** [JohnDMasterson/CS408#1]
Running the program with no base connected causes this error:

```
(gdb) where
#0  0x00000003feda4e88 in libusb_submit_transfer ()
   from /usr/bin/cygusb-1.0.dll
#1  0x00000003feda6a87 in libusb_control_transfer ()
   from /usr/bin/cygusb-1.0.dll
#2  0x000000010040121e in sendIClickerBaseControlTransfer (iBase=0x600039800,
    commandstring=<optimized out>, length=<optimized out>) at iclicker.c:73
#3  0x000000010040136e in setIClickerBaseFrequency (iBase=0x600039800,
    first=<optimized out>, second=<optimized out>) at iclicker.c:118
#4  0x00000001004013f9 in initIClickerBase (iBase=0x600039800)
    at iclicker.c:135
#5  0x0000000100401cba in main () at iclicker.c:225
```

**Comment by 0lumide** [comment]
Now it just silently quits when no base is connected
