### ISSUE TITLE
battleSnakes crash#1

### ISSUE THREAD

**Issue by 0lumide** [JohnDMasterson/CS408#2]
battleSnakes crashes when the snakes collide before eating fruits. This is the error message

```
Traceback (most recent call last):
  File "battleSnakes.py", line 204, in <module>
    gameLoop()
  File "battleSnakes.py", line 76, in gameLoop
    if winner == 1:
UnboundLocalError: local variable 'winner' referenced before assignment
```

**Comment by 0lumide** [comment]
Fixed
